# Generated by Django 4.2.27 on 2025-12-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourited_trails',
            field=models.ManyToManyField(related_name='favourited_by_users', to='trails.trail'),
        ),
    ]
