# Generated by Django 4.2.27 on 2025-12-11 14:48

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trail_type', models.CharField(choices=[('swim', 'Swim'), ('bike', 'Bike'), ('run', 'Run')], max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('city_town', models.CharField(max_length=20)),
                ('latitude', models.FloatField(help_text='Latitude between -90 and 90 degrees', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Longitude between -180 and 180 degrees', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('elevation_gain', models.IntegerField()),
                ('description', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=8)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
