# Generated by Django 4.2.27 on 2025-12-16 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_alter_trail_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='elevation_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude between -90 and 90 degrees', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='trail',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude between -180 and 180 degrees', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
