# Generated by Django 4.2.27 on 2025-12-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_alter_trail_distance_km_alter_trail_elevation_gain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='gpx_url',
            field=models.URLField(blank=True, help_text='Public Cloudinary URL for GPX file', null=True),
        ),
    ]
