# Generated by Django 4.2.27 on 2025-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_trail_gpx_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trail_type',
            field=models.CharField(choices=[('Swim', 'Swim'), ('Bike', 'Bike'), ('Run', 'Run')], max_length=20),
        ),
    ]
