# Generated by Django 4.2.27 on 2025-12-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_alter_trail_trail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trail_type',
            field=models.CharField(choices=[('swim', 'Swim'), ('bike', 'Bike'), ('run', 'Run')], max_length=20),
        ),
    ]
