# Generated by Django 4.2.27 on 2025-12-11 14:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('latitude', models.FloatField(help_text='Latitude between -90 and 90 degrees', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Longitude between -180 and 180 degrees', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
