# Generated by Django 4.2.27 on 2025-12-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='city_town',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
