# Generated by Django 4.2.27 on 2025-12-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
        ('poi', '0002_pointofinterest_city_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to='trails.trail'),
        ),
    ]
