# Generated by Django 4.2.27 on 2025-12-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0003_pointofinterest_trail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofinterest',
            old_name='owner',
            new_name='created_by',
        ),
    ]
