# Generated by Django 4.2.27 on 2025-12-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0004_rename_owner_pointofinterest_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='city_town',
        ),
    ]
